# Generated by Django 6.0.5 on 2026-05-09 12:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ENTREPRISE', 'Entreprise'), ('ENCADRANT', 'Encadrant'), ('ADMIN', 'Admin')], default='ETUDIANT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EncadrantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('specialite', models.CharField(max_length=100)),
                ('bureau', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadrant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('secteur', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('site_web', models.URLField(blank=True)),
                ('ice', models.CharField(max_length=20, unique=True)),
                ('valide', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('CANDIDATURE_RECUE', 'Candidature reçue'), ('STATUT_CHANGE', 'Statut mis à jour'), ('STAGE_EVALUE', 'Stage évalué'), ('ENTREPRISE_VALIDEE', 'Entreprise validée'), ('INFO', 'Information')], default='INFO', max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_stage', models.CharField(choices=[('INITIATION', "Stage d'initiation"), ('PERFECTIONNEMENT', 'Stage de perfectionnement'), ('PFA', 'PFA'), ('PFE', 'PFE')], max_length=20)),
                ('domaine', models.CharField(max_length=100)),
                ('competences', models.TextField(blank=True)),
                ('duree', models.IntegerField()),
                ('remuneration', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('date_limite', models.DateField()),
                ('publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField()),
                ('statut', models.CharField(choices=[('CREEE', 'Créée'), ('EXAMEN', 'En examen'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='CREEE', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='gestion_stage.offrestage')),
            ],
            options={
                'ordering': ['-date_postulation'],
                'unique_together': {('etudiant', 'offre')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé')], default='EN_COURS', max_length=10)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observation', models.TextField(blank=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='gestion_stage.candidature')),
                ('encadrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_encadres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(max_length=20, unique=True)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('1', '1ère année'), ('2', '2ème année'), ('3', '3ème année')], default='2', max_length=5)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
